### ISSUE TITLE
Sequences issue when copying a schema under load

### ISSUE THREAD

**Issue by leshik** [denishpatel/pg-clone-schema#33]
Not sure how this could be addressed.
When copying a schema that is under load (users inserting new records), it's possible sequences become behind the actual table data, which results in duplicate key errors on target.
I'm using a separate SQL now to fix sequences in this case but it would be nice to avoid this issue if possible.

**Comment by MichaelDBA** [comment]
If you have a recommendation, we would be glad to hear it.  Otherwise, I cannot think of a way to make this work nicely when the source schema is under heavy load.

**Comment by MichaelDBA** [comment]
Closing this since it has been idle for a long time.  Again, there is no solution to doing a clone_schema while the database is under a heavy load especially with regard to sequences.  But again, since clone_schema is a function and functions have one implied transaction, i.e., snapshot, I don't see how this could really be a problem in the first place.
