### ISSUE TITLE
Types defined in source_schema should not be used in dest_schema. Cloned type should be used instead

### ISSUE THREAD

**Issue by francoisaubert1** [denishpatel/pg-clone-schema#39]
Hello,
When cloning a table from `source_schema` using a _type_ defined in `source_schema`, I should have my destination table being defined with the _type_ of the destination schema (which is correctly cloned by the way).
It is not the case as the CREATE TABLE LIKE statement will use the source schema _type_ instead.
Help would be much appreciated!

**Comment by MichaelDBA** [comment]
This is not an easy fix since I cannot modify the DDL before it is created.  CREATE LIKE will always use user-defined types specified in the source table, hence the source-qualified type name.  Let me think about this.  In the meantime, I am checking it back in with a WARNING message about the need for manual changes if table columns use user-defined types.

CREATE TABLE sample.address
(   id bigint NOT NULL,
    id2 sample.udt_myint,
    addr text COLLATE pg_catalog."default");

becomes:

CREATE TABLE sample_cloned.address
(
    id bigint NOT NULL,
    **id2 sample.udt_myint,**
    addr text COLLATE pg_catalog."default");

**Comment by MichaelDBA** [comment]
Fixed.  I created a function, get_table_ddl() to use in place of CREATE TABLE LIKE...INCLUDING ALL construct whenever a table with at least one user-defined column type is detected.  It is now part of this project.
