### ISSUE TITLE
Indexes are cloned to the source tablespace

### ISSUE THREAD

**Issue by leshik** [denishpatel/pg-clone-schema#99]
In case the source schema has a tablespace defined, indexes for the cloned schema tables are created in the tablespace of the source schema. I'd expect them to go into the default (empty) tablespace, the same way as with tables.

**Comment by MichaelDBA** [comment]
Hmmm, actually it was a bug in the code that the target table was not being created in the same user-defined tablespace as were the indexes.  Since tablespaces are cluster-wide and not schema-dependent, the design of **clone_schema** regarding tablespaces  was to keep the tablespaces unchanged during the cloning process.  The target tables and indexes should reflect the same tablespace as the source tables and indexes.

Working on fixing this now...

**Comment by MichaelDBA** [comment]
Fixed as designed. Objects are cloned in the target schemas to use the same tablespaces as the source schemas.
